USE [C_CBD];
GO

CREATE TABLE Mensaje(
	[ID_Mensaje] INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	[Contenido] NVARCHAR (MAX) NOT NULL,
	[Fecha_Envio] DATETIME NOT NULL DEFAULT GETDATE(),
	[Remitente] INT NOT NULL,
	[Confirmacion_Lectura] BIT NOT NULL DEFAULT 0,
	[ID_Chat] INT NOT NULL,

	CONSTRAINT FK_Mensaje_Chat
		FOREIGN KEY (ID_Chat)
		REFERENCES Chat(ID_Match)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

		CONSTRAINT FK_Mensaje_Remitente
		FOREIGN KEY (Remitente)
		REFERENCES Perfil(ID_Perfil)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION);

	GO