USE [C_CBD];
GO

CREATE TABLE Chat(
	[ID_Chat] INT IDENTITY (100001,1) PRIMARY KEY NOT NULL,
	[Fecha_Creacion] DATETIME NOT NULL DEFAULT GETDATE(),
	[Mensajes] NVARCHAR(MAX) NULL,
	[ID_Match] INT UNIQUE NOT NULL,

	CONSTRAINT FK_Chat_Match 
		FOREIGN KEY (ID_Match)
		REFERENCES Match(ID_Match)
		ON DELETE CASCADE
		ON UPDATE CASCADE);
	GO