USE [C_CBD];
GO

CREATE TABLE Perfil(
	[ID_Perfil] INT IDENTITY (10001,1) PRIMARY KEY NOT NULL,
	[Nik_Name] NVARCHAR (50) UNIQUE NOT NULL,
	[Biografia] NVARCHAR (500) NULL,
	[Foto_Perfil] VARBINARY (MAX) NULL,
	[ID_Cuenta] INT UNIQUE,
	CONSTRAINT FK_Perfil_Cuenta
		FOREIGN KEY (ID_Cuenta)
		REFERENCES Cuenta(ID_Cuenta)
		ON DELETE CASCADE
		ON UPDATE CASCADE);
	GO