USE [C_CBD];
GO

CREATE TABLE Alumno(
	[Matricula] INT PRIMARY KEY NOT NULL,
	[Nombre] NVARCHAR (50) NOT NULL,
	[Apaterno] NVARCHAR (50) NOT NULL,
	[Amaterno] NVARCHAR (50) NOT NULL,
	[Edad] INT CHECK (Edad BETWEEN 18 AND 30),
	[Genero] CHAR(1) CHECK (GENERO IN ('M', 'F')),
	[Correo] NVARCHAR (50) UNIQUE,
	[Carrera] NVARCHAR (50) NOT NULL);
	GO