IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'dbo')
BEGIN
    EXEC('CREATE SCHEMA dbo');
END;

CREATE TABLE dbo.Cuenta
(
    ID_Cuenta INT IDENTITY(1001,1) PRIMARY KEY,
    Email NVARCHAR(200) NOT NULL UNIQUE,
    Hash_Contrasena NVARCHAR(200) NOT NULL,
    Salt_Contrasena NVARCHAR(200) NOT NULL,
    Estado_Cuenta TINYINT NOT NULL,
    Fecha_Registro DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Alumno
(
    Matricula NVARCHAR(50) NOT NULL PRIMARY KEY,
    ID_Cuenta INT NOT NULL,
    Nombre NVARCHAR(100) NOT NULL,
    Apaterno NVARCHAR(100) NOT NULL,
    Amaterno NVARCHAR(100) NULL,
    F_Nac DATE NOT NULL,
    Genero CHAR(1) NOT NULL,
    Correo NVARCHAR(260) NOT NULL,
    Carrera NVARCHAR(100) NOT NULL,
    Fecha_Registro DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Alumno_Cuenta FOREIGN KEY (ID_Cuenta) REFERENCES dbo.Cuenta(ID_Cuenta) ON DELETE CASCADE
);

CREATE TABLE dbo.Perfil
(
    ID_Perfil INT IDENTITY(1,1) PRIMARY KEY,
    ID_Cuenta INT NOT NULL,
    Nikname NVARCHAR(50) NOT NULL UNIQUE,
    Biografia NVARCHAR(500) NULL,
    FotoPerfil VARBINARY(MAX) NULL,
    FechaCreacion DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Perfil_Cuenta FOREIGN KEY (ID_Cuenta) REFERENCES dbo.Cuenta(ID_Cuenta) ON DELETE CASCADE
);

CREATE TABLE dbo.Match
(
    ID_Match INT IDENTITY(1,1) PRIMARY KEY,
    Perfil_Emisor INT NOT NULL,
    Perfil_Receptor INT NOT NULL,
    Estado NVARCHAR(20) NOT NULL,
    Fecha_Creacion DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    Fecha_Respuesta DATETIME2(0) NULL,
    CONSTRAINT FK_Match_Perfil_Emisor FOREIGN KEY (Perfil_Emisor) REFERENCES dbo.Perfil(ID_Perfil) ON DELETE CASCADE,
    CONSTRAINT FK_Match_Perfil_Receptor FOREIGN KEY (Perfil_Receptor) REFERENCES dbo.Perfil(ID_Perfil) ON DELETE CASCADE
);

CREATE TABLE dbo.Chat
(
    ID_Chat INT IDENTITY(1,1) PRIMARY KEY,
    ID_Match INT NOT NULL,
    Fecha_Creacion DATETIME2(0) NOT NULL DEFAULT SYSUTCDATETIME(),
    LastMessageAtUtc DATETIME2(0) NULL,
    LastMessageId BIGINT NULL,
    CONSTRAINT FK_Chat_Match FOREIGN KEY (ID_Match) REFERENCES dbo.Match(ID_Match)
);

CREATE TABLE dbo.Mensaje
(
    ID_Mensaje BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_Chat INT NOT NULL,
    Remitente INT NOT NULL,
    Contenido NVARCHAR(MAX) NOT NULL,
    Fecha_Envio DATETIME2(0) NOT NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    IsEdited BIT NOT NULL DEFAULT 0,
    Confirmacion_Lectura BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Mensaje_Chat FOREIGN KEY (ID_Chat) REFERENCES dbo.Chat(ID_Chat),
    CONSTRAINT FK_Mensaje_Perfil FOREIGN KEY (Remitente) REFERENCES dbo.Perfil(ID_Perfil) ON DELETE CASCADE
);
